// 영어 단어 데이터 (단어, 뜻)
const WORD_LIST = [
  { word: "abandon", meaning: "버리다, 포기하다" },
  { word: "ability", meaning: "능력, 재능" },
  { word: "absorb", meaning: "흡수하다, 몰두하게 하다" },
  { word: "abstract", meaning: "추상적인, 요약" },
  { word: "abundant", meaning: "풍부한, 많은" },
  { word: "accurate", meaning: "정확한" },
  { word: "achieve", meaning: "달성하다, 이루다" },
  { word: "acknowledge", meaning: "인정하다, 감사하다" },
  { word: "acquire", meaning: "얻다, 습득하다" },
  { word: "adapt", meaning: "적응하다, 개조하다" },
  { word: "adequate", meaning: "적절한, 충분한" },
  { word: "adjust", meaning: "조정하다, 적응하다" },
  { word: "admire", meaning: "존경하다, 감탄하다" },
  { word: "admit", meaning: "인정하다, 허용하다" },
  { word: "adopt", meaning: "채택하다, 입양하다" },
  { word: "advance", meaning: "진보, 전진하다" },
  { word: "advantage", meaning: "이점, 유리함" },
  { word: "advice", meaning: "조언, 충고" },
  { word: "affect", meaning: "영향을 주다" },
  { word: "afford", meaning: "여유가 있다, 감당하다" },
  { word: "aggressive", meaning: "공격적인, 적극적인" },
  { word: "agree", meaning: "동의하다" },
  { word: "aim", meaning: "목표, 겨누다" },
  { word: "allow", meaning: "허용하다" },
  { word: "alter", meaning: "바꾸다, 변경하다" },
  { word: "alternative", meaning: "대안, 대체의" },
  { word: "although", meaning: "비록 ~이지만" },
  { word: "amaze", meaning: "놀라게 하다" },
  { word: "amount", meaning: "양, 금액" },
  { word: "analyze", meaning: "분석하다" },
  { word: "ancient", meaning: "고대의" },
  { word: "announce", meaning: "발표하다, 알리다" },
  { word: "annual", meaning: "연간의, 매년의" },
  { word: "anxious", meaning: "걱정하는, 불안한" },
  { word: "apologize", meaning: "사과하다" },
  { word: "apparent", meaning: "명백한, 겉보기에" },
  { word: "appeal", meaning: "호소하다, 매력" },
  { word: "approach", meaning: "접근하다, 방법" },
  { word: "approve", meaning: "승인하다, 찬성하다" },
  { word: "argue", meaning: "논쟁하다, 주장하다" },
  { word: "arise", meaning: "발생하다, 일어나다" },
  { word: "arrange", meaning: "정리하다, 준비하다" },
  { word: "arrest", meaning: "체포하다" },
  { word: "artificial", meaning: "인공의, 가짜의" },
  { word: "aspect", meaning: "측면, 양상" },
  { word: "assign", meaning: "할당하다, 지정하다" },
  { word: "assume", meaning: "가정하다, 맡다" },
  { word: "attempt", meaning: "시도하다, 시도" },
  { word: "attend", meaning: "참석하다, 돌보다" },
  { word: "attitude", meaning: "태도, 자세" },
  { word: "attract", meaning: "끌어당기다, 끌다" },
  { word: "audience", meaning: "청중, 관객" },
  { word: "available", meaning: "이용 가능한" },
  { word: "average", meaning: "평균, 평균의" },
  { word: "avoid", meaning: "피하다" },
  { word: "aware", meaning: "알고 있는, 인식하는" },
  { word: "balance", meaning: "균형, 균형을 맞추다" },
  { word: "barrier", meaning: "장벽, 장애물" },
  { word: "basic", meaning: "기본적인" },
  { word: "behavior", meaning: "행동, 태도" },
  { word: "benefit", meaning: "이익, 혜택" },
  { word: "beyond", meaning: "~너머에, ~이상" },
  { word: "blame", meaning: "비난하다, 탓하다" },
  { word: "brief", meaning: "짧은, 간단한" },
  { word: "brilliant", meaning: "빛나는, 뛰어난" },
  { word: "budget", meaning: "예산" },
  { word: "burden", meaning: "부담, 짐" },
  { word: "capable", meaning: "할 수 있는, 유능한" },
  { word: "capacity", meaning: "용량, 능력" },
  { word: "career", meaning: "경력, 직업" },
  { word: "cause", meaning: "원인, 일으키다" },
  { word: "celebrate", meaning: "축하하다" },
  { word: "challenge", meaning: "도전, 도전하다" },
  { word: "character", meaning: "성격, 인물" },
  { word: "charge", meaning: "요금, 청구하다" },
  { word: "circumstance", meaning: "상황, 환경" },
  { word: "claim", meaning: "주장하다, 요구하다" },
  { word: "clarify", meaning: "명확히 하다" },
  { word: "climate", meaning: "기후, 분위기" },
  { word: "collapse", meaning: "무너지다, 붕괴" },
  { word: "collect", meaning: "모으다, 수집하다" },
  { word: "combine", meaning: "결합하다" },
  { word: "comfort", meaning: "편안함, 위로" },
  { word: "comment", meaning: "논평, 의견" },
  { word: "commit", meaning: "헌신하다, 범하다" },
  { word: "communicate", meaning: "소통하다, 전달하다" },
  { word: "community", meaning: "공동체, 지역 사회" },
  { word: "compare", meaning: "비교하다" },
  { word: "compete", meaning: "경쟁하다" },
  { word: "complaint", meaning: "불만, 불평" },
  { word: "complex", meaning: "복잡한" },
  { word: "concentrate", meaning: "집중하다" },
  { word: "concept", meaning: "개념" },
  { word: "concern", meaning: "걱정, 관심" },
  { word: "conclude", meaning: "결론 내리다, 끝내다" },
  { word: "condition", meaning: "조건, 상태" },
  { word: "conduct", meaning: "행동하다, 수행하다" },
  { word: "confident", meaning: "자신 있는" },
  { word: "confirm", meaning: "확인하다" },
  { word: "conflict", meaning: "갈등, 충돌" },
  { word: "confuse", meaning: "혼란스럽게 하다" },
  { word: "connect", meaning: "연결하다" },
  { word: "conscious", meaning: "의식하는, 알아채는" },
  { word: "consequence", meaning: "결과, 영향" },
  { word: "consider", meaning: "고려하다" },
  { word: "consist", meaning: "~로 이루어지다" },
  { word: "constant", meaning: "끊임없는, 일정한" },
  { word: "construct", meaning: "건설하다, 구성하다" },
  { word: "contact", meaning: "연락, 접촉" },
  { word: "contain", meaning: "포함하다" },
  { word: "content", meaning: "내용, 만족한" },
  { word: "context", meaning: "맥락, 상황" },
  { word: "continue", meaning: "계속하다" },
  { word: "contract", meaning: "계약, 수축하다" },
  { word: "contrast", meaning: "대조, 대비" },
  { word: "contribute", meaning: "기여하다" },
  { word: "control", meaning: "통제, 조절하다" },
  { word: "convenient", meaning: "편리한" },
  { word: "convince", meaning: "설득하다" },
  { word: "cooperate", meaning: "협력하다" },
  { word: "create", meaning: "창조하다, 만들다" },
  { word: "credit", meaning: "신용, 공로" },
  { word: "crime", meaning: "범죄" },
  { word: "crisis", meaning: "위기" },
  { word: "critical", meaning: "비판적인, 중요한" },
  { word: "culture", meaning: "문화" },
  { word: "curious", meaning: "호기심 많은" },
  { word: "current", meaning: "현재의, 흐름" },
  { word: "damage", meaning: "손상, 피해" },
  { word: "debate", meaning: "논쟁, 토론" },
  { word: "decade", meaning: "10년" },
  { word: "decide", meaning: "결정하다" },
  { word: "declare", meaning: "선언하다, 알리다" },
  { word: "decline", meaning: "거절하다, 감소하다" },
  { word: "decrease", meaning: "감소하다" },
  { word: "defend", meaning: "방어하다" },
  { word: "define", meaning: "정의하다" },
  { word: "degree", meaning: "정도, 학위" },
  { word: "delay", meaning: "지연, 미루다" },
  { word: "deliver", meaning: "배달하다, 전달하다" },
  { word: "demand", meaning: "요구하다, 수요" },
  { word: "demonstrate", meaning: "시연하다, 증명하다" },
  { word: "deny", meaning: "부인하다, 거절하다" },
  { word: "depend", meaning: "의존하다" },
  { word: "describe", meaning: "설명하다" },
  { word: "design", meaning: "설계, 디자인" },
  { word: "desire", meaning: "욕구, 바라다" },
  { word: "despite", meaning: "~에도 불구하고" },
  { word: "destroy", meaning: "파괴하다" },
  { word: "determine", meaning: "결정하다, 밝히다" },
  { word: "develop", meaning: "발전하다, 개발하다" },
  { word: "device", meaning: "기기, 장치" },
  { word: "differ", meaning: "다르다" },
  { word: "difficulty", meaning: "어려움" },
  { word: "dimension", meaning: "차원, 크기" },
  { word: "direct", meaning: "직접의, 지시하다" },
  { word: "disappear", meaning: "사라지다" },
  { word: "disaster", meaning: "재난" },
  { word: "discover", meaning: "발견하다" },
  { word: "discuss", meaning: "논의하다" },
  { word: "disease", meaning: "질병" },
  { word: "display", meaning: "전시하다, 표시" },
  { word: "distance", meaning: "거리" },
  { word: "distribute", meaning: "분배하다" },
  { word: "divide", meaning: "나누다" },
  { word: "document", meaning: "문서, 기록하다" },
  { word: "dominate", meaning: "지배하다" },
  { word: "doubt", meaning: "의심, 의심하다" },
  { word: "dramatic", meaning: "극적인" },
  { word: "economic", meaning: "경제적인" },
  { word: "effective", meaning: "효과적인" },
  { word: "efficient", meaning: "효율적인" },
  { word: "effort", meaning: "노력" },
  { word: "element", meaning: "요소, 원소" },
  { word: "eliminate", meaning: "제거하다" },
  { word: "emerge", meaning: "나타나다, 부상하다" },
  { word: "emotion", meaning: "감정" },
  { word: "emphasis", meaning: "강조" },
  { word: "enable", meaning: "가능하게 하다" },
  { word: "encourage", meaning: "격려하다" },
  { word: "energy", meaning: "에너지, 활력" },
  { word: "engage", meaning: "참여하다, 종사하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "enormous", meaning: "엄청난" },
  { word: "ensure", meaning: "확실히 하다" },
  { word: "environment", meaning: "환경" },
  { word: "equal", meaning: "동등한, 같은" },
  { word: "equipment", meaning: "장비" },
  { word: "essential", meaning: "필수적인" },
  { word: "establish", meaning: "설립하다, 확립하다" },
  { word: "estimate", meaning: "추정하다, 견적" },
  { word: "evaluate", meaning: "평가하다" },
  { word: "evidence", meaning: "증거" },
  { word: "evolve", meaning: "진화하다, 발전하다" },
  { word: "exact", meaning: "정확한" },
  { word: "examine", meaning: "조사하다, 검사하다" },
  { word: "example", meaning: "예시" },
  { word: "exceed", meaning: "초과하다" },
  { word: "exchange", meaning: "교환하다" },
  { word: "exclude", meaning: "제외하다" },
  { word: "expand", meaning: "확장하다" },
  { word: "expect", meaning: "기대하다" },
  { word: "experience", meaning: "경험" },
  { word: "experiment", meaning: "실험" },
  { word: "expert", meaning: "전문가" },
  { word: "explain", meaning: "설명하다" },
  { word: "explore", meaning: "탐험하다, 탐구하다" },
  { word: "export", meaning: "수출하다" },
  { word: "express", meaning: "표현하다" },
  { word: "extend", meaning: "연장하다, 뻗다" },
  { word: "extent", meaning: "범위, 정도" },
  { word: "external", meaning: "외부의" },
  { word: "extra", meaning: "추가의" },
  { word: "extreme", meaning: "극단적인" },
  { word: "factor", meaning: "요인, 요소" },
  { word: "failure", meaning: "실패" },
  { word: "familiar", meaning: "익숙한" },
  { word: "feature", meaning: "특징, 기능" },
  { word: "figure", meaning: "숫자, 인물" },
  { word: "finance", meaning: "재정, 자금" },
  { word: "flexible", meaning: "유연한" },
  { word: "focus", meaning: "집중하다, 초점" },
  { word: "formal", meaning: "공식적인, 격식 있는" },
  { word: "former", meaning: "이전의, 전자" },
  { word: "frequent", meaning: "빈번한" },
  { word: "function", meaning: "기능, 작동하다" },
  { word: "fund", meaning: "자금, 기금" },
  { word: "fundamental", meaning: "근본적인" },
  { word: "generate", meaning: "생성하다" },
  { word: "generous", meaning: "관대한" },
  { word: "genuine", meaning: "진짜의, 진심의" },
  { word: "goal", meaning: "목표" },
  { word: "gradual", meaning: "점진적인" },
  { word: "grant", meaning: "승인하다, 장학금" },
  { word: "guarantee", meaning: "보장하다" },
  { word: "handle", meaning: "다루다, 손잡이" },
  { word: "harsh", meaning: "가혹한, 거친" },
  { word: "hesitate", meaning: "망설이다" },
  { word: "highlight", meaning: "강조하다, 하이라이트" },
  { word: "huge", meaning: "거대한" },
  { word: "identify", meaning: "확인하다, 식별하다" },
  { word: "ignore", meaning: "무시하다" },
  { word: "illustrate", meaning: "설명하다, 그림으로 보여주다" },
  { word: "impact", meaning: "영향, 충격" },
  { word: "implement", meaning: "시행하다, 실행하다" },
  { word: "imply", meaning: "암시하다" },
  { word: "import", meaning: "수입하다" },
  { word: "impress", meaning: "인상 주다" },
  { word: "improve", meaning: "개선하다" },
  { word: "include", meaning: "포함하다" },
  { word: "income", meaning: "소득" },
  { word: "increase", meaning: "증가하다" },
  { word: "indicate", meaning: "나타내다, 가리키다" },
  { word: "individual", meaning: "개인의, 개인" },
  { word: "industry", meaning: "산업" },
  { word: "influence", meaning: "영향, 영향력" },
  { word: "inform", meaning: "알리다" },
  { word: "initial", meaning: "최초의, 첫" },
  { word: "initiative", meaning: "주도권, 계획" },
  { word: "injure", meaning: "다치게 하다" },
  { word: "inner", meaning: "내부의, 내적인" },
  { word: "innovation", meaning: "혁신" },
  { word: "input", meaning: "입력, 기여" },
  { word: "insight", meaning: "통찰, 이해" },
  { word: "install", meaning: "설치하다" },
  { word: "instance", meaning: "사례, 경우" },
  { word: "instead", meaning: "대신에" },
  { word: "intend", meaning: "의도하다" },
  { word: "intense", meaning: "강렬한" },
  { word: "interact", meaning: "상호작용하다" },
  { word: "interest", meaning: "관심, 이자" },
  { word: "internal", meaning: "내부의" },
  { word: "interpret", meaning: "해석하다" },
  { word: "interrupt", meaning: "방해하다, 중단하다" },
  { word: "introduce", meaning: "소개하다, 도입하다" },
  { word: "invest", meaning: "투자하다" },
  { word: "investigate", meaning: "조사하다" },
  { word: "involve", meaning: "관련시키다, 포함하다" },
  { word: "issue", meaning: "문제, 이슈" },
  { word: "item", meaning: "항목, 품목" },
  { word: "journal", meaning: "일지, 학술지" },
  { word: "judge", meaning: "판단하다, 재판관" },
  { word: "justify", meaning: "정당화하다" },
  { word: "label", meaning: "꼬리표, 분류하다" },
  { word: "labor", meaning: "노동, 노력" },
  { word: "lack", meaning: "부족, ~이 없다" },
  { word: "layer", meaning: "층, 레이어" },
  { word: "lead", meaning: "이끌다, 납" },
  { word: "legal", meaning: "법적인" },
  { word: "limit", meaning: "한계, 제한하다" },
  { word: "link", meaning: "연결, 링크" },
  { word: "locate", meaning: "위치를 찾다" },
  { word: "maintain", meaning: "유지하다" },
  { word: "major", meaning: "주요한, 전공" },
  { word: "manage", meaning: "관리하다, 해내다" },
  { word: "manner", meaning: "방식, 태도" },
  { word: "manufacture", meaning: "제조하다" },
  { word: "margin", meaning: "여백, 마진" },
  { word: "material", meaning: "재료, 자료" },
  { word: "maximum", meaning: "최대의" },
  { word: "measure", meaning: "측정하다, 조치" },
  { word: "mediate", meaning: "중재하다" },
  { word: "mental", meaning: "정신적인" },
  { word: "method", meaning: "방법" },
  { word: "minimum", meaning: "최소의" },
  { word: "minor", meaning: "사소한, 미성년자" },
  { word: "modify", meaning: "수정하다" },
  { word: "monitor", meaning: "감시하다, 모니터" },
  { word: "moral", meaning: "도덕적인" },
  { word: "motivate", meaning: "동기 부여하다" },
  { word: "negative", meaning: "부정적인" },
  { word: "negotiate", meaning: "협상하다" },
  { word: "network", meaning: "네트워크" },
  { word: "nevertheless", meaning: "그럼에도 불구하고" },
  { word: "normal", meaning: "정상적인" },
  { word: "notice", meaning: "알아채다, 공지" },
  { word: "obvious", meaning: "명백한" },
  { word: "occur", meaning: "발생하다" },
  { word: "offer", meaning: "제공하다, 제안" },
  { word: "official", meaning: "공식적인" },
  { word: "operate", meaning: "작동하다, 운영하다" },
  { word: "opportunity", meaning: "기회" },
  { word: "oppose", meaning: "반대하다" },
  { word: "option", meaning: "선택지" },
  { word: "ordinary", meaning: "평범한" },
  { word: "organize", meaning: "구성하다, 조직하다" },
  { word: "origin", meaning: "기원, 출처" },
  { word: "original", meaning: "원래의, 독창적인" },
  { word: "outcome", meaning: "결과" },
  { word: "output", meaning: "산출, 출력" },
  { word: "overcome", meaning: "극복하다" },
  { word: "overall", meaning: "전반적인" },
  { word: "participate", meaning: "참여하다" },
  { word: "particular", meaning: "특정한, 특히" },
  { word: "partner", meaning: "파트너, 동반자" },
  { word: "passion", meaning: "열정" },
  { word: "pattern", meaning: "패턴, 양상" },
  { word: "pause", meaning: "멈추다, 일시정지" },
  { word: "payment", meaning: "지불, 결제" },
  { word: "perform", meaning: "수행하다, 공연하다" },
  { word: "period", meaning: "기간, 시기" },
  { word: "permit", meaning: "허용하다, 허가" },
  { word: "persist", meaning: "지속하다, 고집하다" },
  { word: "personal", meaning: "개인의" },
  { word: "perspective", meaning: "관점, 시각" },
  { word: "phase", meaning: "단계, 국면" },
  { word: "phenomenon", meaning: "현상" },
  { word: "physical", meaning: "육체적인, 물리적인" },
  { word: "policy", meaning: "정책" },
  { word: "portion", meaning: "일부, 몫" },
  { word: "positive", meaning: "긍정적인" },
  { word: "potential", meaning: "잠재력, 잠재적인" },
  { word: "practice", meaning: "연습, 관행" },
  { word: "predict", meaning: "예측하다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "prepare", meaning: "준비하다" },
  { word: "present", meaning: "제시하다, 현재의" },
  { word: "preserve", meaning: "보존하다" },
  { word: "pressure", meaning: "압력, 부담" },
  { word: "previous", meaning: "이전의" },
  { word: "primary", meaning: "주요한, 1차적인" },
  { word: "principle", meaning: "원칙" },
  { word: "priority", meaning: "우선순위" },
  { word: "private", meaning: "사적인" },
  { word: "process", meaning: "과정, 처리하다" },
  { word: "produce", meaning: "생산하다" },
  { word: "professional", meaning: "전문적인" },
  { word: "profit", meaning: "이익" },
  { word: "progress", meaning: "진행, 진보" },
  { word: "project", meaning: "프로젝트, 계획" },
  { word: "promote", meaning: "촉진하다, 승진시키다" },
  { word: "propose", meaning: "제안하다" },
  { word: "protect", meaning: "보호하다" },
  { word: "prove", meaning: "증명하다" },
  { word: "provide", meaning: "제공하다" },
  { word: "publish", meaning: "출판하다" },
  { word: "purchase", meaning: "구매하다" },
  { word: "purpose", meaning: "목적" },
  { word: "pursue", meaning: "추구하다" },
  { word: "quality", meaning: "질, 품질" },
  { word: "quantity", meaning: "양" },
  { word: "quote", meaning: "인용하다, 견적" },
  { word: "range", meaning: "범위" },
  { word: "rate", meaning: "비율, 등급" },
  { word: "ratio", meaning: "비율" },
  { word: "rational", meaning: "합리적인" },
  { word: "react", meaning: "반응하다" },
  { word: "realize", meaning: "깨닫다, 실현하다" },
  { word: "reason", meaning: "이유, 추론하다" },
  { word: "recognize", meaning: "인정하다, 알아보다" },
  { word: "recommend", meaning: "추천하다" },
  { word: "reduce", meaning: "줄이다" },
  { word: "refer", meaning: "참조하다, 가리키다" },
  { word: "reflect", meaning: "반영하다, 숙고하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "regard", meaning: "~로 간주하다, 존중" },
  { word: "region", meaning: "지역" },
  { word: "register", meaning: "등록하다" },
  { word: "regret", meaning: "후회하다" },
  { word: "regular", meaning: "규칙적인, 정기적인" },
  { word: "regulate", meaning: "규제하다" },
  { word: "reinforce", meaning: "강화하다" },
  { word: "reject", meaning: "거절하다" },
  { word: "relate", meaning: "관련시키다" },
  { word: "release", meaning: "발표하다, 해제하다" },
  { word: "relevant", meaning: "관련 있는" },
  { word: "relieve", meaning: "완화하다, 덜다" },
  { word: "reluctant", meaning: "마지못해 하는" },
  { word: "rely", meaning: "의존하다" },
  { word: "remain", meaning: "남다" },
  { word: "remark", meaning: "발언, 언급하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "remove", meaning: "제거하다" },
  { word: "replace", meaning: "대체하다" },
  { word: "represent", meaning: "대표하다, 나타내다" },
  { word: "request", meaning: "요청하다" },
  { word: "require", meaning: "요구하다" },
  { word: "research", meaning: "연구" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "resource", meaning: "자원" },
  { word: "respond", meaning: "응답하다" },
  { word: "responsible", meaning: "책임 있는" },
  { word: "restore", meaning: "복원하다" },
  { word: "restrict", meaning: "제한하다" },
  { word: "result", meaning: "결과" },
  { word: "retain", meaning: "유지하다" },
  { word: "reveal", meaning: "드러내다, 공개하다" },
  { word: "review", meaning: "검토하다, 리뷰" },
  { word: "reward", meaning: "보상" },
  { word: "risk", meaning: "위험" },
  { word: "role", meaning: "역할" },
  { word: "route", meaning: "경로" },
  { word: "routine", meaning: "일상, 루틴" },
  { word: "rural", meaning: "시골의" },
  { word: "sample", meaning: "샘플, 표본" },
  { word: "satisfy", meaning: "만족시키다" },
  { word: "scale", meaning: "규모, 척도" },
  { word: "schedule", meaning: "일정" },
  { word: "scheme", meaning: "계획, 방식" },
  { word: "section", meaning: "섹션, 구역" },
  { word: "secure", meaning: "안전한, 확보하다" },
  { word: "select", meaning: "선택하다" },
  { word: "sequence", meaning: "순서, 연속" },
  { word: "series", meaning: "연속, 시리즈" },
  { word: "session", meaning: "세션, 시간" },
  { word: "setting", meaning: "환경, 설정" },
  { word: "settle", meaning: "해결하다, 정착하다" },
  { word: "severe", meaning: "심한, 엄격한" },
  { word: "significant", meaning: "중요한, 상당한" },
  { word: "similar", meaning: "비슷한" },
  { word: "simple", meaning: "단순한" },
  { word: "simulate", meaning: "시뮬레이션하다" },
  { word: "situation", meaning: "상황" },
  { word: "skill", meaning: "기술, 능력" },
  { word: "solution", meaning: "해결책" },
  { word: "solve", meaning: "해결하다" },
  { word: "source", meaning: "출처, 원천" },
  { word: "specific", meaning: "구체적인" },
  { word: "specify", meaning: "명시하다" },
  { word: "sphere", meaning: "영역, 구" },
  { word: "stable", meaning: "안정적인" },
  { word: "standard", meaning: "기준, 표준" },
  { word: "status", meaning: "상태, 지위" },
  { word: "strategy", meaning: "전략" },
  { word: "stress", meaning: "스트레스, 강조하다" },
  { word: "structure", meaning: "구조" },
  { word: "style", meaning: "스타일, 방식" },
  { word: "subject", meaning: "주제, 과목" },
  { word: "submit", meaning: "제출하다" },
  { word: "subsequent", meaning: "이어지는" },
  { word: "substantial", meaning: "상당한, 실질적인" },
  { word: "substitute", meaning: "대체하다, 대체품" },
  { word: "succeed", meaning: "성공하다" },
  { word: "sufficient", meaning: "충분한" },
  { word: "suggest", meaning: "제안하다, 암시하다" },
  { word: "summary", meaning: "요약" },
  { word: "supply", meaning: "공급하다, 공급" },
  { word: "support", meaning: "지원하다, 지지" },
  { word: "suppose", meaning: "가정하다" },
  { word: "survey", meaning: "설문 조사" },
  { word: "survive", meaning: "생존하다" },
  { word: "symbol", meaning: "상징" },
  { word: "symptom", meaning: "증상" },
  { word: "system", meaning: "체계, 시스템" },
  { word: "target", meaning: "목표, 대상" },
  { word: "task", meaning: "과제, 업무" },
  { word: "technique", meaning: "기법, 기술" },
  { word: "technology", meaning: "기술" },
  { word: "temporary", meaning: "일시적인" },
  { word: "tend", meaning: "~하는 경향이 있다" },
  { word: "term", meaning: "용어, 기간" },
  { word: "theme", meaning: "주제, 테마" },
  { word: "theory", meaning: "이론" },
  { word: "therefore", meaning: "그러므로" },
  { word: "threat", meaning: "위협" },
  { word: "throughout", meaning: "~동안 내내" },
  { word: "topic", meaning: "주제" },
  { word: "trace", meaning: "흔적, 추적하다" },
  { word: "tradition", meaning: "전통" },
  { word: "transfer", meaning: "이전하다, 이동" },
  { word: "transform", meaning: "변형시키다" },
  { word: "transition", meaning: "전환, 과도기" },
  { word: "transmit", meaning: "전달하다, 전송하다" },
  { word: "transport", meaning: "수송하다" },
  { word: "trend", meaning: "추세, 트렌드" },
  { word: "trigger", meaning: "촉발하다, 방아쇠" },
  { word: "typical", meaning: "전형적인" },
  { word: "ultimate", meaning: "궁극의" },
  { word: "undergo", meaning: "겪다, 받다" },
  { word: "underline", meaning: "밑줄, 강조하다" },
  { word: "understand", meaning: "이해하다" },
  { word: "undertake", meaning: "착수하다, 맡다" },
  { word: "unique", meaning: "독특한" },
  { word: "universal", meaning: "보편적인" },
  { word: "urban", meaning: "도시의" },
  { word: "urgent", meaning: "긴급한" },
  { word: "utilize", meaning: "활용하다" },
  { word: "valid", meaning: "유효한" },
  { word: "various", meaning: "다양한" },
  { word: "version", meaning: "버전" },
  { word: "virtual", meaning: "가상의" },
  { word: "visible", meaning: "눈에 보이는" },
  { word: "vision", meaning: "비전, 시각" },
  { word: "visual", meaning: "시각적인" },
  { word: "volume", meaning: "양, 볼륨" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "welfare", meaning: "복지" },
  { word: "whereas", meaning: "~인 반면" },
  { word: "widespread", meaning: "널리 퍼진" },
  { word: "withdraw", meaning: "철수하다, 인출하다" },
  { word: "witness", meaning: "목격하다, 목격자" },
  { word: "wonder", meaning: "궁금해하다, 경이" },
  { word: "worth", meaning: "~할 가치가 있는" },
  { word: "yield", meaning: "산출하다, 양보하다" },
];
